# Site Settings
title: Golden Blog | Recueil d'idées pour arrondir ses fins de mois, améliorer son mode de vie, gagner de l'argent sur internet, construire un revenu passif
email: youremail@xyz.com
description: Ce blog à pour but de relater mes différentes expériementations pour mieux vivre financièrement. D'astuces qui peuvent rapporter quelques euros en passant par des techniques qui peuvent vous en rapporter plusieur milliers, tout ce que j'ai pu ou pourra trouver sera relaté ici. Bonne lecture, et à nous la richesse !
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.goldenblog.fr" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Golden Blog
surname: Mr Albert
user_description: Je suis un homme de 25 ans travaillant dans l'informatique, passionné par la musique, et le design.
disqus_username: goldenblog-1

# Social Media
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Accueil
    url: /
  - title: A propos
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
